---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/joshdvir/reflex

steps:
- name: clone
  pull: default
  image: plugins/git
  settings:
    tags: true

- name: release
  pull: default
  image: golang:1.11
  commands:
  - go get -t ./...
  - "curl -sL https://git.io/goreleaser | bash"
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - push
    - tag