project_name: reflex

builds:
  -
    main : .
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

    binary: reflex

archive:
  replacements:
    darwin: Darwin
    linux: Linux

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Linux
  vendor: Josh Dvir
  homepage: https://josh.dvir.co.uk/
  maintainer: Josh Dvir <josh@dvir.us>
  formats:
    - deb

release:
  github:
    owner: joshdvir
    name: reflex
  name_template: "{{.Tag}}"